spring:
  application:
    name: gateway
  rabbitmq:
     host: 47.104.25.22
     port: 5672
     username: guest
     passsword: guest
     virtualHost: /
  data:
    mongodb:
      uri: mongodb://47.104.25.22:27017/microservice_cms
  security:
    user:
      name: admin
      password: admin
server:
  port: 9090